<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Currencies [
        <!ELEMENT Currencies (Updated|SourceURL|Currency)*>
        <!ELEMENT Updated (#PCDATA)>
        <!ELEMENT SourceURL (#PCDATA)>
        <!ELEMENT Currency (CurrencyName|IsoCurrencyCode|IsoCurrencySymbol|CountryNames|IsFund)*>
        <!ELEMENT CurrencyName (#PCDATA)>
        <!ELEMENT IsoCurrencyCode (#PCDATA)>
        <!ELEMENT IsoCurrencySymbol (#PCDATA)>
        <!ELEMENT CountryNames (CountryName)*>
        <!ELEMENT CountryName (#PCDATA)>
        <!ELEMENT IsFund (#PCDATA)>
        ]>
<Currencies>
    <Updated>2024-08-21</Updated>
    <SourceURL>https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml</SourceURL>
    <Currency>
        <CurrencyName>Lek</CurrencyName>
        <IsoCurrencyCode>ALL</IsoCurrencyCode>
        <IsoCurrencySymbol>008</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ALBANIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Algerian Dinar</CurrencyName>
        <IsoCurrencyCode>DZD</IsoCurrencyCode>
        <IsoCurrencySymbol>012</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ALGERIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Argentine Peso</CurrencyName>
        <IsoCurrencyCode>ARS</IsoCurrencyCode>
        <IsoCurrencySymbol>032</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ARGENTINA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Australian Dollar</CurrencyName>
        <IsoCurrencyCode>AUD</IsoCurrencyCode>
        <IsoCurrencySymbol>036</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>AUSTRALIA</CountryName>
            <CountryName>CHRISTMAS ISLAND</CountryName>
            <CountryName>COCOS (KEELING) ISLANDS (THE)</CountryName>
            <CountryName>HEARD ISLAND AND McDONALD ISLANDS</CountryName>
            <CountryName>KIRIBATI</CountryName>
            <CountryName>NAURU</CountryName>
            <CountryName>NORFOLK ISLAND</CountryName>
            <CountryName>TUVALU</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Bahamian Dollar</CurrencyName>
        <IsoCurrencyCode>BSD</IsoCurrencyCode>
        <IsoCurrencySymbol>044</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BAHAMAS (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Bahraini Dinar</CurrencyName>
        <IsoCurrencyCode>BHD</IsoCurrencyCode>
        <IsoCurrencySymbol>048</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BAHRAIN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Taka</CurrencyName>
        <IsoCurrencyCode>BDT</IsoCurrencyCode>
        <IsoCurrencySymbol>050</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BANGLADESH</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Armenian Dram</CurrencyName>
        <IsoCurrencyCode>AMD</IsoCurrencyCode>
        <IsoCurrencySymbol>051</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ARMENIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Barbados Dollar</CurrencyName>
        <IsoCurrencyCode>BBD</IsoCurrencyCode>
        <IsoCurrencySymbol>052</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BARBADOS</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Bermudian Dollar</CurrencyName>
        <IsoCurrencyCode>BMD</IsoCurrencyCode>
        <IsoCurrencySymbol>060</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BERMUDA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Ngultrum</CurrencyName>
        <IsoCurrencyCode>BTN</IsoCurrencyCode>
        <IsoCurrencySymbol>064</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BHUTAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Boliviano</CurrencyName>
        <IsoCurrencyCode>BOB</IsoCurrencyCode>
        <IsoCurrencySymbol>068</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BOLIVIA (PLURINATIONAL STATE OF)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Pula</CurrencyName>
        <IsoCurrencyCode>BWP</IsoCurrencyCode>
        <IsoCurrencySymbol>072</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BOTSWANA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Belize Dollar</CurrencyName>
        <IsoCurrencyCode>BZD</IsoCurrencyCode>
        <IsoCurrencySymbol>084</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BELIZE</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Solomon Islands Dollar</CurrencyName>
        <IsoCurrencyCode>SBD</IsoCurrencyCode>
        <IsoCurrencySymbol>090</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SOLOMON ISLANDS</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Brunei Dollar</CurrencyName>
        <IsoCurrencyCode>BND</IsoCurrencyCode>
        <IsoCurrencySymbol>096</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BRUNEI DARUSSALAM</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Kyat</CurrencyName>
        <IsoCurrencyCode>MMK</IsoCurrencyCode>
        <IsoCurrencySymbol>104</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MYANMAR</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Burundi Franc</CurrencyName>
        <IsoCurrencyCode>BIF</IsoCurrencyCode>
        <IsoCurrencySymbol>108</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BURUNDI</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Riel</CurrencyName>
        <IsoCurrencyCode>KHR</IsoCurrencyCode>
        <IsoCurrencySymbol>116</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CAMBODIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Canadian Dollar</CurrencyName>
        <IsoCurrencyCode>CAD</IsoCurrencyCode>
        <IsoCurrencySymbol>124</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CANADA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Cabo Verde Escudo</CurrencyName>
        <IsoCurrencyCode>CVE</IsoCurrencyCode>
        <IsoCurrencySymbol>132</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CABO VERDE</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Cayman Islands Dollar</CurrencyName>
        <IsoCurrencyCode>KYD</IsoCurrencyCode>
        <IsoCurrencySymbol>136</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CAYMAN ISLANDS (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Sri Lanka Rupee</CurrencyName>
        <IsoCurrencyCode>LKR</IsoCurrencyCode>
        <IsoCurrencySymbol>144</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SRI LANKA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Chilean Peso</CurrencyName>
        <IsoCurrencyCode>CLP</IsoCurrencyCode>
        <IsoCurrencySymbol>152</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CHILE</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Yuan Renminbi</CurrencyName>
        <IsoCurrencyCode>CNY</IsoCurrencyCode>
        <IsoCurrencySymbol>156</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CHINA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Colombian Peso</CurrencyName>
        <IsoCurrencyCode>COP</IsoCurrencyCode>
        <IsoCurrencySymbol>170</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>COLOMBIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Comorian Franc</CurrencyName>
        <IsoCurrencyCode>KMF</IsoCurrencyCode>
        <IsoCurrencySymbol>174</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>COMOROS (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Costa Rican Colon</CurrencyName>
        <IsoCurrencyCode>CRC</IsoCurrencyCode>
        <IsoCurrencySymbol>188</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>COSTA RICA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Cuban Peso</CurrencyName>
        <IsoCurrencyCode>CUP</IsoCurrencyCode>
        <IsoCurrencySymbol>192</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CUBA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Czech Koruna</CurrencyName>
        <IsoCurrencyCode>CZK</IsoCurrencyCode>
        <IsoCurrencySymbol>203</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CZECHIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Danish Krone</CurrencyName>
        <IsoCurrencyCode>DKK</IsoCurrencyCode>
        <IsoCurrencySymbol>208</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>DENMARK</CountryName>
            <CountryName>FAROE ISLANDS (THE)</CountryName>
            <CountryName>GREENLAND</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Dominican Peso</CurrencyName>
        <IsoCurrencyCode>DOP</IsoCurrencyCode>
        <IsoCurrencySymbol>214</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>DOMINICAN REPUBLIC (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>El Salvador Colon</CurrencyName>
        <IsoCurrencyCode>SVC</IsoCurrencyCode>
        <IsoCurrencySymbol>222</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>EL SALVADOR</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Ethiopian Birr</CurrencyName>
        <IsoCurrencyCode>ETB</IsoCurrencyCode>
        <IsoCurrencySymbol>230</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ETHIOPIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Nakfa</CurrencyName>
        <IsoCurrencyCode>ERN</IsoCurrencyCode>
        <IsoCurrencySymbol>232</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ERITREA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Falkland Islands Pound</CurrencyName>
        <IsoCurrencyCode>FKP</IsoCurrencyCode>
        <IsoCurrencySymbol>238</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>FALKLAND ISLANDS (THE) [MALVINAS]</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Fiji Dollar</CurrencyName>
        <IsoCurrencyCode>FJD</IsoCurrencyCode>
        <IsoCurrencySymbol>242</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>FIJI</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Djibouti Franc</CurrencyName>
        <IsoCurrencyCode>DJF</IsoCurrencyCode>
        <IsoCurrencySymbol>262</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>DJIBOUTI</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Dalasi</CurrencyName>
        <IsoCurrencyCode>GMD</IsoCurrencyCode>
        <IsoCurrencySymbol>270</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>GAMBIA (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Gibraltar Pound</CurrencyName>
        <IsoCurrencyCode>GIP</IsoCurrencyCode>
        <IsoCurrencySymbol>292</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>GIBRALTAR</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Quetzal</CurrencyName>
        <IsoCurrencyCode>GTQ</IsoCurrencyCode>
        <IsoCurrencySymbol>320</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>GUATEMALA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Guinean Franc</CurrencyName>
        <IsoCurrencyCode>GNF</IsoCurrencyCode>
        <IsoCurrencySymbol>324</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>GUINEA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Guyana Dollar</CurrencyName>
        <IsoCurrencyCode>GYD</IsoCurrencyCode>
        <IsoCurrencySymbol>328</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>GUYANA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Gourde</CurrencyName>
        <IsoCurrencyCode>HTG</IsoCurrencyCode>
        <IsoCurrencySymbol>332</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>HAITI</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Lempira</CurrencyName>
        <IsoCurrencyCode>HNL</IsoCurrencyCode>
        <IsoCurrencySymbol>340</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>HONDURAS</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Hong Kong Dollar</CurrencyName>
        <IsoCurrencyCode>HKD</IsoCurrencyCode>
        <IsoCurrencySymbol>344</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>HONG KONG</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Forint</CurrencyName>
        <IsoCurrencyCode>HUF</IsoCurrencyCode>
        <IsoCurrencySymbol>348</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>HUNGARY</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Iceland Krona</CurrencyName>
        <IsoCurrencyCode>ISK</IsoCurrencyCode>
        <IsoCurrencySymbol>352</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ICELAND</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Indian Rupee</CurrencyName>
        <IsoCurrencyCode>INR</IsoCurrencyCode>
        <IsoCurrencySymbol>356</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BHUTAN</CountryName>
            <CountryName>INDIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Rupiah</CurrencyName>
        <IsoCurrencyCode>IDR</IsoCurrencyCode>
        <IsoCurrencySymbol>360</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>INDONESIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Iranian Rial</CurrencyName>
        <IsoCurrencyCode>IRR</IsoCurrencyCode>
        <IsoCurrencySymbol>364</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>IRAN (ISLAMIC REPUBLIC OF)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Iraqi Dinar</CurrencyName>
        <IsoCurrencyCode>IQD</IsoCurrencyCode>
        <IsoCurrencySymbol>368</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>IRAQ</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>New Israeli Sheqel</CurrencyName>
        <IsoCurrencyCode>ILS</IsoCurrencyCode>
        <IsoCurrencySymbol>376</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ISRAEL</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Jamaican Dollar</CurrencyName>
        <IsoCurrencyCode>JMD</IsoCurrencyCode>
        <IsoCurrencySymbol>388</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>JAMAICA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Yen</CurrencyName>
        <IsoCurrencyCode>JPY</IsoCurrencyCode>
        <IsoCurrencySymbol>392</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>JAPAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Tenge</CurrencyName>
        <IsoCurrencyCode>KZT</IsoCurrencyCode>
        <IsoCurrencySymbol>398</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>KAZAKHSTAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Jordanian Dinar</CurrencyName>
        <IsoCurrencyCode>JOD</IsoCurrencyCode>
        <IsoCurrencySymbol>400</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>JORDAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Kenyan Shilling</CurrencyName>
        <IsoCurrencyCode>KES</IsoCurrencyCode>
        <IsoCurrencySymbol>404</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>KENYA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>North Korean Won</CurrencyName>
        <IsoCurrencyCode>KPW</IsoCurrencyCode>
        <IsoCurrencySymbol>408</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Won</CurrencyName>
        <IsoCurrencyCode>KRW</IsoCurrencyCode>
        <IsoCurrencySymbol>410</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>KOREA (THE REPUBLIC OF)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Kuwaiti Dinar</CurrencyName>
        <IsoCurrencyCode>KWD</IsoCurrencyCode>
        <IsoCurrencySymbol>414</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>KUWAIT</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Som</CurrencyName>
        <IsoCurrencyCode>KGS</IsoCurrencyCode>
        <IsoCurrencySymbol>417</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>KYRGYZSTAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Lao Kip</CurrencyName>
        <IsoCurrencyCode>LAK</IsoCurrencyCode>
        <IsoCurrencySymbol>418</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Lebanese Pound</CurrencyName>
        <IsoCurrencyCode>LBP</IsoCurrencyCode>
        <IsoCurrencySymbol>422</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>LEBANON</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Loti</CurrencyName>
        <IsoCurrencyCode>LSL</IsoCurrencyCode>
        <IsoCurrencySymbol>426</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>LESOTHO</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Liberian Dollar</CurrencyName>
        <IsoCurrencyCode>LRD</IsoCurrencyCode>
        <IsoCurrencySymbol>430</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>LIBERIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Libyan Dinar</CurrencyName>
        <IsoCurrencyCode>LYD</IsoCurrencyCode>
        <IsoCurrencySymbol>434</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>LIBYA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Pataca</CurrencyName>
        <IsoCurrencyCode>MOP</IsoCurrencyCode>
        <IsoCurrencySymbol>446</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MACAO</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Malawi Kwacha</CurrencyName>
        <IsoCurrencyCode>MWK</IsoCurrencyCode>
        <IsoCurrencySymbol>454</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MALAWI</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Malaysian Ringgit</CurrencyName>
        <IsoCurrencyCode>MYR</IsoCurrencyCode>
        <IsoCurrencySymbol>458</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MALAYSIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Rufiyaa</CurrencyName>
        <IsoCurrencyCode>MVR</IsoCurrencyCode>
        <IsoCurrencySymbol>462</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MALDIVES</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Mauritius Rupee</CurrencyName>
        <IsoCurrencyCode>MUR</IsoCurrencyCode>
        <IsoCurrencySymbol>480</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MAURITIUS</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Mexican Peso</CurrencyName>
        <IsoCurrencyCode>MXN</IsoCurrencyCode>
        <IsoCurrencySymbol>484</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MEXICO</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Tugrik</CurrencyName>
        <IsoCurrencyCode>MNT</IsoCurrencyCode>
        <IsoCurrencySymbol>496</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MONGOLIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Moldovan Leu</CurrencyName>
        <IsoCurrencyCode>MDL</IsoCurrencyCode>
        <IsoCurrencySymbol>498</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MOLDOVA (THE REPUBLIC OF)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Moroccan Dirham</CurrencyName>
        <IsoCurrencyCode>MAD</IsoCurrencyCode>
        <IsoCurrencySymbol>504</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>MOROCCO</CountryName>
            <CountryName>WESTERN SAHARA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Rial Omani</CurrencyName>
        <IsoCurrencyCode>OMR</IsoCurrencyCode>
        <IsoCurrencySymbol>512</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>OMAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Namibia Dollar</CurrencyName>
        <IsoCurrencyCode>NAD</IsoCurrencyCode>
        <IsoCurrencySymbol>516</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>NAMIBIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Nepalese Rupee</CurrencyName>
        <IsoCurrencyCode>NPR</IsoCurrencyCode>
        <IsoCurrencySymbol>524</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>NEPAL</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Netherlands Antillean Guilder</CurrencyName>
        <IsoCurrencyCode>ANG</IsoCurrencyCode>
        <IsoCurrencySymbol>532</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>CURAÇAO</CountryName>
            <CountryName>SINT MAARTEN (DUTCH PART)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Aruban Florin</CurrencyName>
        <IsoCurrencyCode>AWG</IsoCurrencyCode>
        <IsoCurrencySymbol>533</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>ARUBA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Vatu</CurrencyName>
        <IsoCurrencyCode>VUV</IsoCurrencyCode>
        <IsoCurrencySymbol>548</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>VANUATU</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>New Zealand Dollar</CurrencyName>
        <IsoCurrencyCode>NZD</IsoCurrencyCode>
        <IsoCurrencySymbol>554</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>COOK ISLANDS (THE)</CountryName>
            <CountryName>NEW ZEALAND</CountryName>
            <CountryName>NIUE</CountryName>
            <CountryName>PITCAIRN</CountryName>
            <CountryName>TOKELAU</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Cordoba Oro</CurrencyName>
        <IsoCurrencyCode>NIO</IsoCurrencyCode>
        <IsoCurrencySymbol>558</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>NICARAGUA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Naira</CurrencyName>
        <IsoCurrencyCode>NGN</IsoCurrencyCode>
        <IsoCurrencySymbol>566</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>NIGERIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Norwegian Krone</CurrencyName>
        <IsoCurrencyCode>NOK</IsoCurrencyCode>
        <IsoCurrencySymbol>578</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>BOUVET ISLAND</CountryName>
            <CountryName>NORWAY</CountryName>
            <CountryName>SVALBARD AND JAN MAYEN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Pakistan Rupee</CurrencyName>
        <IsoCurrencyCode>PKR</IsoCurrencyCode>
        <IsoCurrencySymbol>586</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>PAKISTAN</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Balboa</CurrencyName>
        <IsoCurrencyCode>PAB</IsoCurrencyCode>
        <IsoCurrencySymbol>590</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>PANAMA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Kina</CurrencyName>
        <IsoCurrencyCode>PGK</IsoCurrencyCode>
        <IsoCurrencySymbol>598</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>PAPUA NEW GUINEA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Guarani</CurrencyName>
        <IsoCurrencyCode>PYG</IsoCurrencyCode>
        <IsoCurrencySymbol>600</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>PARAGUAY</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Sol</CurrencyName>
        <IsoCurrencyCode>PEN</IsoCurrencyCode>
        <IsoCurrencySymbol>604</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>PERU</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Philippine Peso</CurrencyName>
        <IsoCurrencyCode>PHP</IsoCurrencyCode>
        <IsoCurrencySymbol>608</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>PHILIPPINES (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Qatari Rial</CurrencyName>
        <IsoCurrencyCode>QAR</IsoCurrencyCode>
        <IsoCurrencySymbol>634</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>QATAR</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Russian Ruble</CurrencyName>
        <IsoCurrencyCode>RUB</IsoCurrencyCode>
        <IsoCurrencySymbol>643</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>RUSSIAN FEDERATION (THE)</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Rwanda Franc</CurrencyName>
        <IsoCurrencyCode>RWF</IsoCurrencyCode>
        <IsoCurrencySymbol>646</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>RWANDA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Saint Helena Pound</CurrencyName>
        <IsoCurrencyCode>SHP</IsoCurrencyCode>
        <IsoCurrencySymbol>654</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Saudi Riyal</CurrencyName>
        <IsoCurrencyCode>SAR</IsoCurrencyCode>
        <IsoCurrencySymbol>682</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SAUDI ARABIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Seychelles Rupee</CurrencyName>
        <IsoCurrencyCode>SCR</IsoCurrencyCode>
        <IsoCurrencySymbol>690</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SEYCHELLES</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Singapore Dollar</CurrencyName>
        <IsoCurrencyCode>SGD</IsoCurrencyCode>
        <IsoCurrencySymbol>702</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SINGAPORE</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Dong</CurrencyName>
        <IsoCurrencyCode>VND</IsoCurrencyCode>
        <IsoCurrencySymbol>704</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>VIET NAM</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Somali Shilling</CurrencyName>
        <IsoCurrencyCode>SOS</IsoCurrencyCode>
        <IsoCurrencySymbol>706</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>SOMALIA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>
        <CurrencyName>Rand</CurrencyName>
        <IsoCurrencyCode>ZAR</IsoCurrencyCode>
        <IsoCurrencySymbol>710</IsoCurrencySymbol>
        <CountryNames>
            <CountryName>LESOTHO</CountryName>
            <CountryName>NAMIBIA</CountryName>
            <CountryName>SOUTH AFRICA</CountryName>
        </CountryNames>
    </Currency>
    <Currency>